#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pico/stdlib.h"
#include "hardware/gpio.h"
#include "third_party/pawn/amx.h"
#include "blink_amx.h"

// Default LED pin for Seeed Studio XIAO RP2040
#ifndef LED_PIN
#define LED_PIN 25
#endif

// Native function: set_led(status)
static cell AMX_NATIVE_CALL n_set_led(AMX *amx, const cell *params) {
    (void)amx;
    gpio_put(LED_PIN, params[1]);
    return 0;
}

// Native function: delay(ms)
static cell AMX_NATIVE_CALL n_delay(AMX *amx, const cell *params) {
    (void)amx;
    sleep_ms(params[1]);
    return 0;
}

// Native function: print(const string[])
static cell AMX_NATIVE_CALL n_print(AMX *amx, const cell *params) {
    char *str;
    amx_StrParam(amx, params[1], str);
    if (str != NULL) {
        printf("%s", str);
    }
    return 0;
}

static const AMX_NATIVE_INFO led_natives[] = {
    { "set_led", n_set_led },
    { "delay",   n_delay },
    { "print",   n_print },
    { NULL, NULL }
};

// Required by Pawn
int AMXEXPORT amx_CoreInit(AMX *amx);
int AMXEXPORT amx_CoreCleanup(AMX *amx);

void amx_ErrorHandler(AMX *amx, int error) {
    (void)amx;
    printf("Pawn error %d\n", error);
}

int main() {
    stdio_init_all();
    gpio_init(LED_PIN);
    gpio_set_dir(LED_PIN, GPIO_OUT);

    printf("Pawn LED Runtime Starting...\n");

    AMX amx;
    cell ret = 0;
    int err;

    // The blink_amx array is generated by xxd from blink.amx
    // We need to copy it to a mutable buffer because Pawn might modify it (e.g. for relocation)
    void *program = malloc(blink_amx_len);
    if (program == NULL) {
        printf("Failed to allocate memory for Pawn program\n");
        return 1;
    }
    memcpy(program, blink_amx, blink_amx_len);

    memset(&amx, 0, sizeof(amx));
    err = amx_Init(&amx, program);
    if (err != AMX_ERR_NONE) {
        printf("amx_Init failed with error %d\n", err);
        return 1;
    }

    // Register native functions
    amx_Register(&amx, led_natives, -1);

    printf("Executing Pawn script...\n");
    err = amx_Exec(&amx, &ret, AMX_EXEC_MAIN);
    if (err != AMX_ERR_NONE) {
        printf("amx_Exec failed with error %d\n", err);
    }

    printf("Pawn script finished with return value %ld\n", (long)ret);

    amx_Cleanup(&amx);
    free(program);

    while (true) {
        // Fallback heartbeat
        gpio_put(LED_PIN, 1);
        sleep_ms(100);
        gpio_put(LED_PIN, 0);
        sleep_ms(900);
    }

    return 0;
}
